apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rag-platform.fullname" . }}-qdrant
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "rag-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  accessModes:
    - {{ .Values.persistence.qdrant.accessMode }}
  storageClassName: {{ .Values.persistence.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.qdrant.size }}
